# Generated by Django 4.2.1 on 2023-07-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_updated_at_like_content_type_like_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.UUIDField(verbose_name='Content Object ID'),
        ),
    ]
